CREATE TABLE USERMEMBER
(
    ID VARCHAR2(16 BYTE) NOT NULL PRIMARY KEY,
    PWD VARCHAR2(16 BYTE) NOT NULL,
    NAME VARCHAR2(30 BYTE) NOT NULL,
    WORKPLACE VARCHAR2(30 BYTE) NOT NULL,
    SALPERHOUR VARCHAR2(16 BYTE) NOT NULL
);
--ALTER TABLE USERMEMBER ADD CONSTRAINT USERMEMBER_ID_FK FOREIGN KEY(NO) REFERENCES;
INSERT INTO USERMEMBER VALUES ('jooy311','12345','이주영','투썸플레이스','7300');

select * from usermember;

CREATE TABLE PAYMANAGER (
    USERID VARCHAR2(16) NOT NULL,
    WORKDATE VARCHAR2(13) NOT NULL,
    WORKDATEY NUMBER(5) NOT NULL,
    WORKDATEM NUMBER(3) NOT NULL,
    WORKDATED NUMBER(3) NOT NULL,
    STARTTIME VARCHAR2(6) NOT NULL,
    ENDTIME VARCHAR2(6) NOT NULL,
    WORKTIME VARCHAR2(10) NOT NULL,
    DAYSAL VARCHAR2(8) NOT NULL,
    CONSTRAINT PAYMANAGER_WORKDATE_USERID_PK PRIMARY KEY(WORKDATE, USERID),
    CONSTRAINT PAYMANAGER_ID_FK FOREIGN KEY(USERID) REFERENCES USERMEMBER(ID)
);
DROP TABLE PAYMANAGER;
ALTER TABLE PAYMANAGER ADD CONSTRAINT PAYMANAGER_WORKDATE_PK PRIMARY KEY(WORKDATE);
INSERT INTO PAYMANAGER VALUES ('jooy311','2020/6/11','2020', '6', '12','8:30','17:30','9:00','65700');
COMMIT;
ROLLBACK;
select * FROM PAYMANAGER;
INSERT INTO PAYMANAGER VALUES ('dotolee11','2020/6/11','2020', '6', '11','8:30','17:30','9:00','65700');
SELECT  WORKDATEY, WORKDATEM, WORKDATED, STARTTIME, ENDTIME, WORKTIME, DAYSAL FROM PAYMANAGER JOIN USERMEMBER ON PAYMANAGER.USERID = USERMEMBER.ID WHERE USERMEMBER.ID = 'jooy311' ORDER BY WORKDATEY,WORKDATEM,WORKDATED;
SELECT * FROM PAYMANAGER WHERE USERID = 'jooy311' ORDER BY WORKDATEY,WORKDATEM,WORKDATED;

